---

- name: package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ nginx_package }}"
    - libselinux-python
  tags: 
  - nginx

- name: enable
  service:
    name: "{{ nginx_service }}"
    enabled: true
  tags: 
  - nginx

- name: config
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf }}"
  notify:
    - restart nginx
  tags: 
  - nginx
