---
galaxy_info:
  author: Daniel Chalk
  description: php-fpm
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  galaxy_tags:
    - php
    - php-fpm
dependencies:
  - role: epel