---
- name: user
  user:
    name: "{{ web_user }}"
    home: "{{ web_home_dir }}"
    shell: /sbin/nologin

- stat:
    path: "{{ web_build_dir }}"
  register: stat_web_build_dir

- stat:
    path: "{{ web_current_path }}"
  register: stat_web_current_path

- name: builds dir
  file:
    dest: "{{ web_build_dir }}"
    state: directory
    owner: "{{ web_user }}"

- name: test dir
  file:
    dest: "{{ web_build_dir }}/test"
    state: directory
    owner: "{{ web_user }}"
  when: stat_web_current_path.stat.isdir is not defined

- name: test index
  copy:
    dest: "{{ web_build_dir }}/test/index.html"
    src: "index.html"
    owner: "{{ web_user }}"
  when: stat_web_current_path.stat.isdir is not defined

- name: test symlink
  file:
    src: "{{ web_build_dir }}/test"
    dest: "{{ web_current_path }}"
    owner: "{{ web_user }}"
    state: link
  when: stat_web_current_path.stat.isdir is not defined

- name: php-fpm service
  service:
    name: "{{ web_service_php }}"
    enabled: true

- name: php-fpm config
  template:
    src: fpm-pool.conf.j2
    dest: /etc/php-fpm.d/www.conf
  notify:
    - restart php-fpm
