---

- name: packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ web_packages }}"

- include: app.yml

- name: enable
  service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - "{{ web_service_nginx }}"

- name: nginx config
  template:
    src: nginx.conf.j2
    dest: /opt/rh/nginx16/root/etc/nginx/nginx.conf
  notify:
    restart nginx
