---
- name: packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ web_packages }}"

- name: enable
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - "{{ web_service_nginx }}"
