---
- name: nginx vhost
  template:
    src: vhost.conf.j2
    dest: "{{ nginx_conf_dir }}/{{ app_name }}.conf"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  notify:
    - restart nginx
  tags:
    - app
    - nginx

- name: nginx disable default vhost
  file:
    dest: "{{ nginx_conf_dir }}/default.conf"
    state: absent
  notify:
    - restart nginx
  tags:
    - app
    - nginx